---
{{- if .Values.keycloakInstanceOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.keycloakInstanceOperator.name }}
  annotations:
    {{- toYaml .Values.keycloakInstanceOperator.serviceAccount.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ .Values.keycloakInstanceOperator.name }}
    app.kubernetes.io/version: {{ .Values.keycloakInstanceOperator.image.tag }}
    app.kubernetes.io/managed-by: quarkus
{{- end }}
