apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edp-{{ .Values.keyclaokEdpOperator.name }}-rolebinding
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edp-{{ .Values.keyclaokEdpOperator.name }}-role
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.keyclaokEdpOperator.name }}
